#!/bin/sh
set -e
cp /etc/apache2/mods-available/proxy.load /etc/apache2/mods-enabled/proxy.load
cp /etc/apache2/mods-available/proxy_http.load /etc/apache2/mods-enabled/proxy_http.load

if [ $host ];then
sed -i -e "s|ProxyPass /mt/ http://localhost:5000/mt/ timeout=600 keepalive=Off|ProxyPass /mt/ $host:5000/mt/ timeout=600 keepalive=Off|g" /etc/apache2/sites-available/000-default.conf
sed -i -e "s|ProxyPassReverse /mt/ http://localhost:5000/mt/|ProxyPassReverse /mt/ $host:5000/mt/|g" /etc/apache2/sites-available/000-default.conf
fi;
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi
cat /etc/apache2/sites-available/000-default.conf
exec "$@"